version: '3'
services:
  web:
    image: nginx
    container_name: system_electoral_web
    restart: always
    volumes:
      - .:/app/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - ${APP_PORT}:80
    depends_on:
     - php
    networks:
      - local-network
      - public-network
  php:
    build:
      context: ./docker/php/
    container_name: system_electoral_php
    working_dir: /app
    image: php:7.2-fpm
    tty: true
    restart: always
    volumes:
      - .:/app/
    networks:
        - local-network
  db:
    image: mariadb
    restart: always
    container_name: system_electoral_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    ports: 
      - 3306:3306
    networks:
      - local-network
networks:
  local-network:
  public-network:

volumes:
  dbdata:
  medicaldata:
